services:
  react:
    build: .
    ports:
      - '5173:5173'
      - '24678:24678'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    restart: always
